replicaCount: 1
namespace: dev
image:
  repository: 436469730160.dkr.ecr.ap-southeast-1.amazonaws.com/productpage
  tag: dev-b8d935efa591e01d7fae2564068c66f5d8010179
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ecr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 80
app:
  name: productpage
serviceAccountName: ecr-sa
imagePullSecrets:
  - name: ecr-secret
