replicaCount: 1
namespace: dev
image:
  repository: 585008089219.dkr.ecr.ap-southeast-1.amazonaws.com/productpage
  tag: 9f452dd7e98ae950124e127548383c03e5cafab5
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ecr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
