replicaCount: 1
namespace: dev
image:
  repository: 585008089219.dkr.ecr.ap-southeast-1.amazonaws.com/productpage
  tag: 9a0a17cff50ae3894459039c44e0635a877d1c98
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ecr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
