replicaCount: 1
namespace: dev
image:
  repository: 436469730160.dkr.ecr.ap-southeast-1.amazonaws.com/productpage
  tag: dev-fd599a4b9ccfb3cef1816057b98b91ef65798ef1
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ecr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 80
app:
  name: productpage
serviceAccountName: ecr-sa
imagePullSecrets:
  - name: ecr-secret
