replicaCount: 1
namespace: main
image:
  repository: 436469730160.dkr.ecr.ap-southeast-1.amazonaws.com/productpage
  tag: main-fb7ad02408c5867df26d5edaf321cb59f72b1118
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ecr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 80
app:
  name: productpage
serviceAccountName: ecr-sa
imagePullSecrets:
  - name: ecr-secret
