replicaCount: 1
namespace: dev
image:
  repository: 123456789012.dkr.ecr.ap-southeast-1.amazonaws.com/productpage
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

serviceAccount:
  create: true
  name: bookinfo-dev-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::585008089219:role/BookinfoEKSPodRole